services:
  tts:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: rk3576-tts:latest
    container_name: rk3576-tts
    privileged: true
    network_mode: host
    volumes:
      - /dev:/dev
      - /home/cat/qwen3-tts-rknn:/opt/tts/models:ro
      - /home/cat/models/talker_fullvocab_fixed_w4a16_rk3576.rkllm:/opt/tts/models/talker_fullvocab_fixed_w4a16_rk3576.rkllm:ro
    restart: unless-stopped
    environment:
      - MODEL_DIR=/opt/tts/models
